# charts/charts/keycloak/charts/keycloak/templates/post-install-job.yaml
# https://helm.sh/docs/topics/charts_hooks/
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "keycloak.fullname" . }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - build
            - --vault=file
