apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  admin: {{ .Values.admin.password |b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin-password
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  password: {{ .Values.admin.password |b64enc }}
