#!/usr/bin/env python3
import os
import re
import yaml

def getValues(subchart):
    valuesYaml = ""
    isHeader = True
    isGlobal = False
    with open(subchart) as f:
        for line in f:
            if line.startswith('#') and isHeader:
                continue
            else:
                isHeader = False
            if isGlobal and line.startswith('  '):
                continue
            else:
                isGlobal = False
            if line.startswith('global:'):
                isGlobal = True
                continue
            valuesYaml += "  "+line
    return valuesYaml

def main():
    valuesYaml = ""
    isSubchart = False
    chartValues = {}

    with open("Chart.yaml") as f:
        chart = yaml.safe_load(f)
    for d in chart['dependencies']:
        _values = "charts/{}/values.yaml".format(d['name'])
        if os.path.isfile(_values):
            chartValues[d['name']] = getValues(_values)

    subcharts = sorted(list(chartValues.keys()))

    with open("values.yaml") as f:
        for line in f:
            subchart = [e for e in subcharts if line.startswith("{}:".format(e))]
            if subchart:
                valuesYaml += "{}:".format(subchart[0]) +os.linesep
                valuesYaml += chartValues[subchart[0]]
                subcharts.remove(subchart[0])
                isSubchart = True
                continue
            if isSubchart and line.startswith('  '):
                continue
            else:
                isSubchart = False
            valuesYaml += line

        for _subchart in subcharts:
            valuesYaml += "{}:".format(_subchart) +os.linesep
            valuesYaml += chartValues[_subchart]

    with open("values.yaml", 'w') as f:
        f.write(valuesYaml)

if __name__ == '__main__':
    main()
